### ISSUE TITLE
FB Graph API - how will access to multiple groups work

### ISSUE THREAD

**Issue by alecfrancesconi** [Data4Democracy/ati-broadcastapp#2]
We know that the API supports multiple requests but can those requests span multiple groups in the same HTTP request and how will the access tokens work

**Comment by nausicaa-rose** [comment]
Facebook Graph API
==================
The Facebook Graph API makes it fairly easy to post to multiple groups with a minimal number of HTTP requests. By using batch requests, we can post to up to 50 groups at a time (which should mean 1 request for smaller states). To set up access tokens, we'll have to connect our app to the user's Facebook account, and get a User Access Token. There is a [React SDK](https://developers.facebook.com/docs/react-native) that should help in setting this up. Once we have an access token, we should be able to post to any group the user is a member of. Further documentation on access tokens [can be found here](https://developers.facebook.com/docs/facebook-login/access-tokens/).

Here's a summary of the data fields we'll need to create, update, and delete posts.

To post to group
-----------------
- From user login:
  - user-id
  - access token
- From Facebook API:
  - group-id (should store these in Mongo as part of the group documents. I'll see if there's a way to scrape 
    this and add that functionality to our scrapper if I can.)

To update/delete post
---------------------
  - From user login:
    - user-id
    - access token
  - From Facebook API:
    - post-id

[Facebook documents these operations here.](https://developers.facebook.com/docs/graph-api/reference/v2.9/post)

[Facebook batch requests are documented here](https://developers.facebook.com/docs/graph-api/making-multiple-requests/). There is currently a limit of 50 requests per batch. Batch requests are sent as a JSON
array of HTTP requests.

When messages are posted, the API returns the post-id, so we need to make sure
we capture and store those in case we need to update or delete a post.

**Comment by jonganc** [comment]
I'm going to refactor this issue into more current ones.
