### ISSUE TITLE
Wireframe 1: Login Page

### ISSUE THREAD

**Issue by kflanagan** [Data4Democracy/ati-broadcastapp#33]
1.0: User story 1. Assumes use of Google Security. Page ﬂow may be diﬀerent. App will authorize the user to the speciﬁc state they have permissions to post

![image](https://user-images.githubusercontent.com/1428220/31748634-82ee90b4-b442-11e7-8e0d-86f12f53d545.png)

**Comment by jonganc** [comment]
While not necessarily beautiful, this is done.
