### ISSUE TITLE
Wireframe 4a: Post to FB

### ISSUE THREAD

**Issue by kflanagan** [Data4Democracy/ati-broadcastapp#37]
1.0: Notiﬁcation of intent to post. Includes number of groups included in this post. We should be able to tabulate based on active groups in the db. 2.0: Posts to groups in selected state 3.0 Returns user to edit screen User story 6

![image](https://user-images.githubusercontent.com/1428220/31749131-00896b7c-b446-11e7-9f8e-5b479f8e0810.png)

**Comment by jonganc** [comment]
This is done.
